### ISSUE TITLE
Doubts about the inlier_threshold param

### ISSUE THREAD

**Issue by fb82** [SuhZhang/DeMatch#1]
Hi,

the `inlier_threshold` parameter is set to `2.0` in the `demo` folder script, and `0.` in the `test` folder script. Which value is preferable for testing on data from `yfcc100m` and `sun3d`, respectively?

Thanks!

**Comment by SuhZhang** [comment]
Thanks for attention. 
We choose `inlier_threshold=0` for all methods during verification. 
However, we have proved in [another work (ConvMatch, Figure 7)](https://ieeexplore.ieee.org/abstract/document/10323178) that the best threshold is not 0 and it varies from different methods, we set the threshold as 0 just for fair comparison and easy implementation. In the `demo` we set the threshold as `2.0` just for better visualization, and actually `2.0` performs better for testing on data from `yfcc100m` and `sun3d`.

**Comment by fb82** [comment]
Thanks!
